"""Alembic environment for the Marine Data Layer canonical schema.

This migration environment is intentionally **model-agnostic**: it does NOT
import backend-owned SQLAlchemy models (those are owned by the backend
workstream). Migrations are written as explicit operations so the platform
layer can provision/evolve the canonical schema, PostGIS geometry columns and
TimescaleDB hypertables independently, while coordinating field-for-field with
the documented canonical entity dictionary (requirements §7, source_mapping §7).

The database URL is taken from the DATABASE_URL environment variable so no
credentials are stored in alembic.ini.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Inject the runtime database URL (psycopg v3 driver, matches pyproject).
_db_url = os.environ.get("DATABASE_URL")
if _db_url:
    config.set_main_option("sqlalchemy.url", _db_url)

# No target_metadata: migrations are explicit (not autogenerated) to avoid
# importing backend models. Autogenerate is intentionally unavailable here.
target_metadata = None


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL without a DBAPI connection)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode with a live connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
